### PR TITLE
Auto-follow new projects for listed admins

### PR DESCRIPTION
**Pull request by aquilax**
#1245 Calls `trackProject` for user ids defined in `conf.ini` section`site.autofollow_admin_ids`.

Note: the extra changes in `conf.template.ini` are removed trailing space.

RFR @alanbarrett

### CODE REVIEW

**Comment by alanbarrett** [comment]
@aquilax 

Two things...

1) Could you set up a pull request against develop, this one is against master which I know you did not intend.

2) I have a worry about the behavior of the code in the following cased, could you tell me what the return value is from getAutoFollowAdminIds() in the following cases  (it should be an empty array)...

a) no autofollow_admin_ids setting in the config file.
b) autofollow_admin_ids= in the config file (i.e. no values as you have in the default config)

Explode generates an array of length one when given an empty string (which will be casted to 0)... I do not know if (a) or (b) give an empty string.

    Alan.

**Comment by aquilax** [comment]
Hi @alanbarrett 

2. You are right for this one. Added a check for empty string.
1. Will close this pull request and create new one targeting `develop`. Related to that, how often master is the target of a pull request? Since we mostly target `develop`, I'd suggest to make it the default branch if you agree.

**Comment by alanbarrett** [comment]
If we change to develop, will a git clone then pick the develop branch by
default (I do not know if this is so), which is not what we want?

    Alan.

**Comment by aquilax** [comment]
It shouldn't affect `git`. according to the [documentation](https://git-scm.com/docs/git-clone):
> After the clone, a plain git fetch without arguments will update all the remote-tracking branches, and a git pull without arguments will in addition merge the remote master branch into the current master branch, if any (this is untrue when "--single-branch" is given; see below).

https://help.github.com/articles/setting-the-default-branch/:

> The default branch is considered the base branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch.

**Comment by alanbarrett** [comment]
But it also says before this...
"Clones a repository into a newly created directory, ..., and creates and
checks out an initial branch that is forked from the cloned repository’s
currently active branch."
...this "currently active branch" might be "develop".

However go ahead with your plan to make "develop" the default, I will add a
specific "git checkout master" to the instruction in the Wiki so there can
be no problem.

    Alan.

**Comment by aquilax** [comment]
Decided check instead of guessing https://github.com/aquilax/test.git .Seems like github indeed changes the head and the default becomes `develop` . Still worth it IMO.

**Comment by alanbarrett** [comment]
Yes please change.

    Alan.

**Comment by alanbarrett** [comment]
@aquilax I have changed default to develop for SOLAS-Match, not sure if you have rights to do that.

    Alan.

**Comment by aquilax** [comment]
:+1:

**Pull request closed without merging**
